### ISSUE TITLE
Additional licensing details?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-opensci/ResourceBook#3]
**Is your feature request related to a problem? Please describe.**
- I think MIT is another good option for a [license](https://nmfs-opensci.github.io/ResourceBook/content/licenses_gov.html). It is suitable for software and isn't a copy left license, which makes it less restrictive than GPL.
- Maybe include some details about other steps that should be followed when choosing a license, in particular verifying that all coding collaborators agree to the license. 
- link https://r-pkgs.org/license.html

**Describe the solution you'd like**
I am happy to submit a PR to add this to the licensing page, but wanted to propose the idea first!

**Describe alternatives you've considered**
Leave as-is.

**Additional context**

**Comment by eeholmes** [comment]
More details here would be a good addition. I have not seen the MIT license used for government work. Have you? 

One thing we have to considered is work that involves contractors. A discussion about the license and specification in the contract that all work by contractor will be public domain would be a good thing. 

When I publish papers, this is sometimes a bit tricky. Me (or any government FTE) being on a paper means that it cannot be copy-righted so we have to go through extra steps with the journal. Same with books.

**Comment by k-doering-NOAA** [comment]
Thanks, Eli, I've seen it used in packages that aren't explicitly just developed by FTEs, such as ss3sim (https://github.com/ss3sim/ss3sim). I have used it in my own work sometimes. But I also haven't looks specifically at government packages.

The takeaways I have come away with after looking into licensing for gov't work is that open source licenses should be acceptable, and the more permissive the better (the nuances are confusing, as you well know!). I personally am not a big fan of GPL, because it is a copy left, which means derivative works must also use the GPL license, which to me, feels too restrictive, given it is common practice in science to copy/paste chunks of code for use in a new package without realizing that the same GPL license is supposed to be used in the new package. MIT allows copy/paste without needing to also have the same license. Here's a little bit on [r4ss licensing](https://github.com/r4ss/r4ss/issues/625) that doesn't illuminate much other than licensing isn't straightforward!

**Comment by eeholmes** [comment]
Great info! Go ahead and add some background on the licenses for the page.  I personally have been using CC 1.0 but mainly because I didn't understand all the nuances and CC 1.0 seemed super permissive.

**Comment by k-doering-NOAA** [comment]
Yes it is super permissive, and I've seen CC0 used widely and be recommended for government work.

The only issues I see are 1) the folks behind CC0 itself [do not recommend the license for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), which does seem like a big problem and 2) if you want to publish your tool in the Journal of Open Source Software, CC0 is not acceptable because it is not one of the listed open source licenses on [the open source initiative](https://opensource.org/).

I'll put together a PR with some of this info, then, since it seems helpful!

**Comment by eeholmes** [comment]
Thanks! This is very helpful for sure. I'd kind of known that re CC0, but hadn't done the research to figure out something better.

**Comment by eeholmes** [comment]
Added more info in the last few commits
